// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRv9qk8PI2uLp6JXQGrhrc9ZYlwpUzJJE',
    appId: '1:915956914124:web:4d059cc5eb1afa7ff5af69',
    messagingSenderId: '915956914124',
    projectId: 'date-planner-d5054',
    authDomain: 'date-planner-d5054.firebaseapp.com',
    storageBucket: 'date-planner-d5054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5yNb75iRpBTv7m9RtX4KCXMvurWxKLw',
    appId: '1:915956914124:android:a9c954d3e6cb66e4f5af69',
    messagingSenderId: '915956914124',
    projectId: 'date-planner-d5054',
    storageBucket: 'date-planner-d5054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjLfzCJxMdXXiCTsCsit_CYudC0TNrdZg',
    appId: '1:915956914124:ios:98cafb2f22a21e5af5af69',
    messagingSenderId: '915956914124',
    projectId: 'date-planner-d5054',
    storageBucket: 'date-planner-d5054.appspot.com',
    androidClientId: '915956914124-p0bhctl6sg3jn08dpju7ud21ibpk4g9q.apps.googleusercontent.com',
    iosClientId: '915956914124-b5vjfih7o3g1cd2t26n0ullbu1cpupb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBoringTo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjLfzCJxMdXXiCTsCsit_CYudC0TNrdZg',
    appId: '1:915956914124:ios:98cafb2f22a21e5af5af69',
    messagingSenderId: '915956914124',
    projectId: 'date-planner-d5054',
    storageBucket: 'date-planner-d5054.appspot.com',
    androidClientId: '915956914124-p0bhctl6sg3jn08dpju7ud21ibpk4g9q.apps.googleusercontent.com',
    iosClientId: '915956914124-b5vjfih7o3g1cd2t26n0ullbu1cpupb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBoringTo',
  );
}
